### ISSUE TITLE
It cannot load canvas.js

### ISSUE THREAD

**Issue by Drachenbauer** [file-acomplaint/knottingham#1]
I downloaded the project and opened it´s html-file through microsoft edge, because i cannot find an online running version on the web.
But it cannot load canvas.js and outputs this error:

`paper.js:14337  Access to XMLHttpRequest at 'file:///D:/Mods/knottingham-main/knottingham-main/js/canvas.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, isolated-app, chrome-extension, chrome-untrusted, https, edge.
request @ paper.js:14337
paper.js:14337 
        
        
        Failed to load resource: net::ERR_FAILED
request @ paper.js:14337
paper.js:14337  Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///D:/Mods/knottingham-main/knottingham-main/js/canvas.js'.
    at Object.request (file:///D:/Mods/knottingham-main/knottingham-main/lib/paper.js:14337:14)
    at HTMLCollection.loadScript (file:///D:/Mods/knottingham-main/knottingham-main/lib/paper.js:17405:10)
    at HTMLCollection.forIn (file:///D:/Mods/knottingham-main/knottingham-main/lib/paper.js:56:11)
    at Function.each (file:///D:/Mods/knottingham-main/knottingham-main/lib/paper.js:75:7)
    at loadAll (file:///D:/Mods/knottingham-main/knottingham-main/lib/paper.js:17422:8)
index.html:33  Uncaught TypeError: window.globals.draw is not a function
    at HTMLButtonElement.onclick (index.html:33:202)`

How do i get it to work local?

**Comment by lennart-finke** [comment]
Hello and thanks for using knottingham!

You have two options:

1. Serve a local webserver with `npx http-server --cors` for which you need to install npm.
2. Allow CORS on localhost. I don't recommend you to do this as it comes with security risks. Therefore I need to stress that you would be doing this at your own accountability only. It looks like you are using Edge, so it might also be needed to switch browsers.

**Comment by Drachenbauer** [comment]
Does this work with the free version, too?
On the npm page there are 3 membership-versions:
One free for only public packages and 2 paid, that allow local packages too.

Never mind.

I have python already installed and followed this instruction:
https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Tools_and_setup/set_up_a_local_testing_server
Now it seems to work.
